# Generated by Django 2.2.4 on 2021-01-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210119_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='action',
        ),
        migrations.RemoveField(
            model_name='show',
            name='release',
        ),
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='desc',
            field=models.TextField(),
        ),
    ]
